### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by tobi437a** [AzizKpln/Moriarty-Project#13]
I tried to search for a phone number and got this error

Owner Name/Number Information:

Traceback (most recent call last):
  File "Moriarty.py", line 177, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 59, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by AzizKpln** [comment]
Did u run the installation file?

**Comment by tobi437a** [comment]
Yes i did

**Comment by AzizKpln** [comment]
I just realized something. I have to make some changes in installation file. I Will update the tool tomorrow.

**Comment by tobi437a** [comment]
Okay thanks

**Comment by AzizKpln** [comment]
can you try to install it again?

**Comment by tobi437a** [comment]
I installed it again and now when i search i get this.

Traceback (most recent call last):
  File "Moriarty.py", line 177, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 59, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/home/tobi437a/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by AzizKpln** [comment]
What OS are you using?

**Comment by tobi437a** [comment]
Im using the Kali Linux terminal on Windows

**Comment by AzizKpln** [comment]
i released the version 2.6 you won't be encountring with this error anymore i believe.
