### ISSUE TITLE
Failure at the end

### ISSUE THREAD

**Issue by BlueSkyN** [AzizKpln/Moriarty-Project#14]
I used telephone number tracking and it worked but finally it gived a fail:

Traceback (most recent call last):                                                                                                                                             
  File "Moriarty.py", line 201, in <module>                                                                                                                                    
    deep_info_two(options.phone_number)                                                                                                                                        
  File "Moriarty.py", line 154, in deep_info_two                                                                                                                               
    deep_info2.deep_two(phone_number)                                                                                                                                          
  File "/root/Moriarty-Project/risks_and_deep_search/deep_info2.py", line 29, in deep_two                                                                                      
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[1]/div/form/input"))).send_keys(phone_number)                                 
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 86, in until                                                                          
    raise TimeoutException(message, screen, stacktrace)                                                                                                                        
selenium.common.exceptions.TimeoutException: Message:

**Comment by AzizKpln** [comment]
I'll check it soon

**Comment by AzizKpln** [comment]
it's updated. You won't be encountring with this error anymore <3

**Comment by BlueSkyN** [comment]
Thanks for your attention.

Aziz Kaplan <notifications@github.com>, 26 Kas 2020 Per, 16:51 tarihinde
şunu yazdı:
