### ISSUE TITLE
Search Failed

### ISSUE THREAD

**Issue by itgelo** [AzizKpln/Moriarty-Project#16]
I got an error. what's the solution?
_OS: Ubuntu
Version: 18.04
User: Non-Root_

```
Traceback (most recent call last):
  File "Moriarty.py", line 179, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 59, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/home/user/.local/lib/python3.6/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 100, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
```

**Comment by AzizKpln** [comment]
Use the latest version of a Debian based OS.
(i tested it on kali Linux 2020.4. It works without recieving an error.)

**Comment by tellhimisaid** [comment]
I am currently trying to use this on the current version of Parrot OS. I am getting the same problem. Is there a workaround for using Parrot instead of Kali?
Also I only get this error when not using a space between "-p" and the email password. If I use a space between the option and the password the return is always "error: --p option requires 1 argument.
