### ISSUE TITLE
Problem to identification

### ISSUE THREAD

**Issue by Noegs** [AzizKpln/Moriarty-Project#20]
hi Aziz, i have problem with this one 

Owner Name/Number Information:

Traceback (most recent call last):
  File "Moriarty.py", line 179, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 62, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/form[1]/div/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/input[1]"))).send_keys(username)
  File "/home/oegeks/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

what suppose to do?

**Comment by jepunband** [comment]
same issue here:

Traceback (most recent call last):
  File "Moriarty.py", line 179, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 61, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/main/div/a[2]"))).click()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Pyreaus** [comment]
I have the same issue

**Comment by NataliSemi** [comment]
I have the same issue ....

**Comment by AzizKpln** [comment]
Tool has been updated. You won't be encountering with errors.
