### ISSUE TITLE
undetected_chromedriver

### ISSUE THREAD

**Issue by highrider0602** [AzizKpln/Moriarty-Project#23]
after install and i try to run tool i get this error 

 python3 Moriarty.py -h
Traceback (most recent call last):
  File "/opt/Moriarty-Project/Moriarty.py", line 17, in <module>
    from social_media import facebook
  File "/opt/Moriarty-Project/social_media/facebook.py", line 17, in <module>
    import undetected_chromedriver as uc
ModuleNotFoundError: No module named 'undetected_chromedriver'

tried to apt-cache cearch for the chromedriver it says i am missing but search yields no results.

**Comment by highrider0602** [comment]
so ended up loosing all my data due to dell repair depot for their work fixing my no power issue on my laptop recently, had to reinstall fresh kali again loosing everything, but after doing a fresh install of this tool, i now am getting this output that i cant figure out why or what im doing wrong. 


Owner Name/Number Information:                                                                                                                             
                                                                                                                                                           
Traceback (most recent call last):                                                                                                                         
  File "/root/Desktop/Moriarty-Project/Moriarty.py", line 179, in <module>                                                                                 
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)                                                              
  File "/root/Desktop/Moriarty-Project/Moriarty.py", line 61, in microsoft_mail                                                                            
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/main/div/a[2]"))).click()                                        
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click                                                         
    self._execute(Command.CLICK_ELEMENT)                                                                                                                   
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 672, in _execute                                                     
    return self._parent.execute(command, params)                                                                                                           
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute                                                       
    self.error_handler.check_response(response)                                                                                                            
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response                                             
    raise exception_class(message, screen, stacktrace)                                                                                                     
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a data-v-716b6b0d="" href="https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&amp;respone_mode=query&amp;client_id=000000004818BA61&amp;redirect_uri=https://www.truecaller.com/auth/microsoft/callback&amp;scope=openid profile email User.Read Contacts.Read" class="flex items-center py-3 pl-4 pr-2 rounded bg-panelColor border border-borderColor text-fontPrimaryColor text-xs font-semibold w-full max-w-sm mb-4 hover:bg-panelHoverColor cursor-not-allowed pointer-events-none text-fontSecondaryColor opacity-60">...</a> is not clickable at point (392, 327). Other element would receive the click: <div data-v-716b6b0d="" class="container max-w-sm py-12 relative">...</div>                                                                                                                            
  (Session info: headless chrome=89.0.4389.82)   


there were no errors during install or anything, i am root user, fresh install of kali was earlier today a few hours prior to reinstalling this tool. not sure why i cant get this to work for me, any tips would be welcome.

**Comment by AzizKpln** [comment]
Moriarty-Project doesn't work properly at the moment.

**Comment by highrider0602** [comment]
> Moriarty-Project doesn't work properly at the moment.

oh i see, bummer. is it going to work again sometime?
