### ISSUE TITLE
Huge error 

### ISSUE THREAD

**Issue by jasonsalem2002** [AzizKpln/Moriarty-Project#24]
Traceback (most recent call last):                                                                          
  File "/home/jay/Moriarty-Project/Moriarty.py", line 179, in <module>                                      
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)               
  File "/home/jay/Moriarty-Project/Moriarty.py", line 59, in microsoft_mail                                 
    driver = uc.Chrome(options=options)                                                                     
  File "/home/jay/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__                                                                                                          
    instance.__init__(*args, **kwargs)                                                                      
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__        
    RemoteWebDriver.__init__(                                                                               
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__       
    self.start_session(capabilities, browser_profile)                                                       
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session  
    response = self.execute(Command.NEW_SESSION, parameters)                                                
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute        
    self.error_handler.check_response(response)                                                             
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response                                                                                                          
    raise exception_class(message, screen, stacktrace)                                                      
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89                                                                       
Current browser version is 88.0.4324.182 with binary path /usr/bin/chromium

I installed the program without sudo permission everything was good but when i run the program with my outlook and pass it doesn't work. Is this tool still getting updated or abandoned?

**Comment by AzizKpln** [comment]
Tool has been updated. You won't be encountering with errors.
