### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by lijinta1984** [AzizKpln/Moriarty-Project#27]
Traceback (most recent call last):
  File "/home/lijin/Moriarty-Project/Moriarty.py", line 168, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "/home/lijin/Moriarty-Project/Moriarty.py", line 58, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/home/lijin/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 51, in __new__
    instance.__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 92, in __init__
    self.service.start()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/service.py", line 104, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./chromedriver

**Comment by D3m0ni4k** [comment]
Don't work on Android

**Comment by AzizKpln** [comment]
Hello,
The issue is fixed. You can try to re-install it
