### ISSUE TITLE
in line #166 of moriart.py 

### ISSUE THREAD

**Issue by frogtasty** [AzizKpln/Moriarty-Project#32]
i am on kali linux and running it as non root
everything was fine  but after running              python3    Moriaty.py   -n  +1-202-555-0125  
i am getting the error
                                                                                                                   
Traceback (most recent call last):                                                                                 
  File "/home/frog/Desktop/Moriarty-Project/Moriarty.py", line 166, in <module>                                    
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)                      
  File "/home/frog/Desktop/Moriarty-Project/Moriarty.py", line 61, in microsoft_mail                               
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.NAME, "loginfmt"))).send_keys(username)         
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webelement.py", line 511, in send_keys            
    {'text': "".join(keys_to_typing(value)),                                                                       
  File "/usr/lib/python3/dist-packages/selenium/webdriver/common/utils.py", line 153, in keys_to_typing            
    for i in range(len(val)):                                                                                      
TypeError: object of type 'NoneType' has no len()

**Comment by Modasirkhan** [comment]
same problem of me

**Comment by realKarthikNair** [comment]
Read the readme properly , a microsoft account is MANDATORY

**Comment by AzizKpln** [comment]
Updated
