### ISSUE TITLE
Bug : TimeOut Error

### ISSUE THREAD

**Issue by parulgarg123** [AzizKpln/Moriarty-Project#34]
Getting Below Error when trying to execute the command mentioned in ReadMe doc.

```
Owner Name/Number Information:

Traceback (most recent call last):
  File "Moriarty.py", line 166, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 62, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/form[1]/div/div/div/div[2]/div/div/div[1]/div[3]/div/div/div/div[4]/div/div/div/div[2]/input"))).click()
  File "/Library/Python/3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by gokullan** [comment]
Raised a pull request. Check it out...

**Comment by AzizKpln** [comment]
Updated
