### ISSUE TITLE
chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by RobertoTorino** [AzizKpln/Moriarty-Project#40]
Running on Windows10 WSL2 Ubuntu-20.04, throws this error, any ideas?
Edit got a new error, the previous is gone now:
``
Traceback (most recent call last):
  File "Moriarty.py", line 166, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 60, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/main/div/a[2]"))).click()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a data-v-5d22f278="" href="https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&amp;respone_mode=query&amp;client_id=000000004818BA61&amp;redirect_uri=https://www.truecaller.com/auth/microsoft/callback&amp;scope=openid profile email User.Read" class="flex items-center py-3 pl-4 pr-2 rounded bg-panelColor border border-borderColor text-fontPrimaryColor text-xs font-semibold w-full max-w-sm mb-4 hover:bg-panelHoverColor">...</a> is not clickable at point (392, 327). Other element would receive the click: <p data-v-039ea216="" class="cd__text">...</p>
  (Session info: headless chrome=92.0.4515.107)
``
Deprecated error:
``
Traceback (most recent call last):
  File "Moriarty.py", line 166, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 58, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/usr/local/lib/python3.8/dist-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127
``

**Comment by AzizKpln** [comment]
Updated
