### ISSUE TITLE
all packages are install correctly but still not running

### ISSUE THREAD

**Issue by qwezxcmp130743** [AzizKpln/Moriarty-Project#41]
Traceback (most recent call last):
  File "Moriarty.py", line 166, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 58, in microsoft_mail
    driver = uc.Chrome(options=options)
  File "/mnt/d/wubuntu/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by Username-Nos** [comment]
I'm having the same issue. I'm using WSL - Windows 64bit with 32 GB RAM, on an i5 system.

I've reinstalled Chrome/Chromium, even made a new OSint-outlook as well to no avail, and even configured the moriarty.py so that it used an older version (one I copied from commit histories) with no success. I've found this problem is persistent on Raspian and Debian as well as Ubuntu Linux Server.

**Comment by AzizKpln** [comment]
Updated
