### ISSUE TITLE
OutlookAccount/username.moriarty Not found

### ISSUE THREAD

**Issue by meetgyn** [AzizKpln/Moriarty-Project#51]
When running the script I get this error.
Python3 Moriarty.py - -no -social media -rf -Pn +55xxxxxxxxx

Traceback (most recent call last):
  File "/opt/osint/Moriarty-Project/Moriarty.py", line 171, in <module>
    MP=Moriarty_Project()
  File "/opt/osint/Moriarty-Project/Moriarty.py", line 34, in __init__
    self.getLoginInfoQuick()
  File "/opt/osint/Moriarty-Project/Moriarty.py", line 48, in getLoginInfoQuick
    with open("OutlookAccount/username.moriarty","r") as username:self.username=username.read()
FileNotFoundError: [Errno 2] No such file or directory: 'OutlookAccount/username.moriarty'

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
