### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by imakealol** [AzizKpln/Moriarty-Project#53]
I've got the following error. Anyone have an idea how to fix the problem??

[+]Country:Germany
[+]Time Zone:Europe/Berlin
[+]Carrier:O2
Traceback (most recent call last):
  File "Moriarty.py", line 175, in <module>
    MP.run()
  File "Moriarty.py", line 145, in run
    self.spamcalls_()
  File "Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "C:\Users\The_Trickster80\projekte\Moriarty-Project\DeepInfo\risks.py", line 8, in __init__
    display=Display(visible=0,size=(1024, 768))
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\site-packages\pyvirtualdisplay\display.py", line 54, in __init__
    self._obj = cls(
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\site-packages\pyvirtualdisplay\xvfb.py", line 44, in __init__
    AbstractDisplay.__init__(
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\site-packages\pyvirtualdisplay\abstractdisplay.py", line 85, in __init__
    helptext = get_helptext(program)
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\site-packages\pyvirtualdisplay\util.py", line 13, in get_helptext
    p = subprocess.Popen(
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\The_Trickster80\.pyenv\pyenv-win\versions\3.8.1\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
