### ISSUE TITLE
Doesn t work  - error log.

### ISSUE THREAD

**Issue by Andrejki** [AzizKpln/Moriarty-Project#54]
```
Traceback (most recent call last):
  File "Moriarty.py", line 175, in <module>
    MP.run()
  File "Moriarty.py", line 145, in run
    self.spamcalls_()
  File "Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/home/andrejki/Moriarty-Project/DeepInfo/risks.py", line 8, in __init__
    display=Display(visible=0,size=(1024, 768))
  File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/display.py", line 54, in __init__
    self._obj = cls(
  File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/xvfb.py", line 44, in __init__
    AbstractDisplay.__init__(
  File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/abstractdisplay.py", line 85, in __init__
    helptext = get_helptext(program)
  File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/util.py", line 13, in get_helptext
    p = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'
```

Hi, this is the error. Thank you kindly for this, but it just doesn t work?
Best regards

**Comment by teslatrader** [comment]
> ```
> Traceback (most recent call last):
>   File "Moriarty.py", line 175, in <module>
>     MP.run()
>   File "Moriarty.py", line 145, in run
>     self.spamcalls_()
>   File "Moriarty.py", line 122, in spamcalls_
>     spamcalls().spamcallsStart(self.phoneNumber)
>   File "/home/andrejki/Moriarty-Project/DeepInfo/risks.py", line 8, in __init__
>     display=Display(visible=0,size=(1024, 768))
>   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/display.py", line 54, in __init__
>     self._obj = cls(
>   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/xvfb.py", line 44, in __init__
>     AbstractDisplay.__init__(
>   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/abstractdisplay.py", line 85, in __init__
>     helptext = get_helptext(program)
>   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/util.py", line 13, in get_helptext
>     p = subprocess.Popen(
>   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'
> ```
> 
> Hi, this is the error. Thank you kindly for this, but it just doesn t work? Best regards

I faced the same. Just install the pip: sudo apt-get install xvfb

**Comment by wehackpeople** [comment]
Not working.
Traceback (most recent call last):
  File "/opt/osint-numbersearch/./Moriarty.py", line 175, in <module>
    MP.run()
  File "/opt/osint-numbersearch/./Moriarty.py", line 145, in run
    self.spamcalls_()
  File "/opt/osint-numbersearch/./Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/opt/osint-numbersearch/DeepInfo/risks.py", line 10, in __init__
    self.driver=uc.Chrome(options=options,version_main=f.read())
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:48727
from chrome not reachable

**Comment by Andrejki** [comment]
> > ```
> > Traceback (most recent call last):
> >   File "Moriarty.py", line 175, in <module>
> >     MP.run()
> >   File "Moriarty.py", line 145, in run
> >     self.spamcalls_()
> >   File "Moriarty.py", line 122, in spamcalls_
> >     spamcalls().spamcallsStart(self.phoneNumber)
> >   File "/home/andrejki/Moriarty-Project/DeepInfo/risks.py", line 8, in __init__
> >     display=Display(visible=0,size=(1024, 768))
> >   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/display.py", line 54, in __init__
> >     self._obj = cls(
> >   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/xvfb.py", line 44, in __init__
> >     AbstractDisplay.__init__(
> >   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/abstractdisplay.py", line 85, in __init__
> >     helptext = get_helptext(program)
> >   File "/home/andrejki/.local/lib/python3.8/site-packages/pyvirtualdisplay/util.py", line 13, in get_helptext
> >     p = subprocess.Popen(
> >   File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hi, this is the error. Thank you kindly for this, but it just doesn t work? Best regards
> 
> I faced the same. Just install the package: sudo apt-get install xvfb

Thanks, but not helpful, did that, nothing.
 The hotmail account is valid and the password. 
 I guess it just doesn t want to work. 
 ```
Traceback (most recent call last):
 
  File "Moriarty.py", line 175, in <module>
    MP.run()
  File "Moriarty.py", line 145, in run
    self.spamcalls_()
  File "Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/home/andrejki/Moriarty-Project/DeepInfo/risks.py", line 10, in __init__
    self.driver=uc.Chrome(options=options,version_main=f.read())
  File "/home/andrejki/.local/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 233, in __init__
    patcher.auto()
  File "/home/andrejki/.local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "/home/andrejki/.local/lib/python3.8/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bijoy26** [comment]
Experiencing the same issue in `Kali 2020.1`. I have `Chromium v103.0.5060.134` installed.

**Comment by hxhBrofessor** [comment]
after adding the additional `--no-sandbox` arguments I was able to fix the chrome unreachable error. 

## Fix unreachable chrome issue

```
	def startChrome(self):
		try:
			f=open("Moriarty/c_Version.moriarty","r")
			options = uc.ChromeOptions()
			options.add_argument("--no-sandbox")
			options.add_argument(version_main=f.read())
			self.driver=uc.Chrome(options=options, delay=30)
		except FileNotFoundError:
			os.system("cd Moriarty && bash c_V.sh && cd ..")
			f=open("Moriarty/c_Version.moriarty","r")
			self.driver=uc.Chrome(options=options, delay=30)

```

But now getting the following error below. 

## Error
```
Traceback (most recent call last):
  File "/opt/Moriarty-Project/DeepInfo/risks.py", line 32, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[1]/div[1]/div/h3/strong"))).text 
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5625102afcd3 <unknown>
#1 0x5625100b7968 <unknown>
#2 0x5625100eefd7 <unknown>
#3 0x5625100ef1a1 <unknown>
#4 0x562510122154 <unknown>
#5 0x56251010cbdd <unknown>
#6 0x56251011fea8 <unknown>
#7 0x56251010caa3 <unknown>
#8 0x5625100e23fa <unknown>
#9 0x5625100e3555 <unknown>
#10 0x5625102f72bd <unknown>
#11 0x5625102fb418 <unknown>
#12 0x5625102e136e <unknown>
#13 0x5625102fc078 <unknown>
#14 0x5625102d5bb0 <unknown>
#15 0x562510318d58 <unknown>
#16 0x562510318ed8 <unknown>
#17 0x562510332cfd <unknown>
#18 0x7fca47ee9b43 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Moriarty-Project/DeepInfo/risks.py", line 45, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/span[2]"))).text 
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5625102afcd3 <unknown>
#1 0x5625100b7968 <unknown>
#2 0x5625100eefd7 <unknown>
#3 0x5625100ef1a1 <unknown>
#4 0x562510122154 <unknown>
#5 0x56251010cbdd <unknown>
#6 0x56251011fea8 <unknown>
#7 0x56251010caa3 <unknown>
#8 0x5625100e23fa <unknown>
#9 0x5625100e3555 <unknown>
#10 0x5625102f72bd <unknown>
#11 0x5625102fb418 <unknown>
#12 0x5625102e136e <unknown>
#13 0x5625102fc078 <unknown>
#14 0x5625102d5bb0 <unknown>
#15 0x562510318d58 <unknown>
#16 0x562510318ed8 <unknown>
#17 0x562510332cfd <unknown>
#18 0x7fca47ee9b43 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Moriarty-Project/Moriarty.py", line 178, in <module>
    MP.run()
  File "/opt/Moriarty-Project/Moriarty.py", line 148, in run
    self.spamcalls_()
  File "/opt/Moriarty-Project/Moriarty.py", line 125, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/opt/Moriarty-Project/DeepInfo/risks.py", line 57, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/h4"))).text
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5625102afcd3 <unknown>
#1 0x5625100b7968 <unknown>
#2 0x5625100eefd7 <unknown>
#3 0x5625100ef1a1 <unknown>
#4 0x562510122154 <unknown>
#5 0x56251010cbdd <unknown>
#6 0x56251011fea8 <unknown>
#7 0x56251010caa3 <unknown>
#8 0x5625100e23fa <unknown>
#9 0x5625100e3555 <unknown>
#10 0x5625102f72bd <unknown>
#11 0x5625102fb418 <unknown>
#12 0x5625102e136e <unknown>
#13 0x5625102fc078 <unknown>
#14 0x5625102d5bb0 <unknown>
#15 0x562510318d58 <unknown>
#16 0x562510318ed8 <unknown>
#17 0x562510332cfd <unknown>
#18 0x7fca47ee9b43 <unknown>


```

**Comment by AzizKpln** [comment]
Hi, I'm moving this project to playwright. And I'll remove cli usage. Everything will be on web.
Note :  This project doesn't work currently

**Comment by Iyanuu** [comment]
@AzizKpln spent the last 2 hours trying to figure out what I was doing wrong. I guess we just have to wait now.

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
