### ISSUE TITLE
Selenium got stuck in spamcallsStart

### ISSUE THREAD

**Issue by teslatrader** [AzizKpln/Moriarty-Project#55]
Traceback (most recent call last):
  File "Moriarty-Project/DeepInfo/risks.py", line 32, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[1]/div[1]/div/h3/strong"))).text 
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556d5f1fbe89 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Moriarty-Project/DeepInfo/risks.py", line 45, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/span[2]"))).text 
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556d5f1fbe89 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Moriarty.py", line 175, in <module>
    MP.run()
  File "Moriarty.py", line 145, in run
    self.spamcalls_()
  File "Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "Moriarty-Project/DeepInfo/risks.py", line 57, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/h4"))).text
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556d5f1fbe89 <unknown>

Hope you will find time to adjust your awesome product.

**Comment by AzizKpln** [comment]
Hello, this project needs an update. Im thinking of moving this project from selenium to playwright but currently I don't have time for an update. But I will update this tool when Im available. Thanks for your interest in this project.

**Comment by teslatrader** [comment]
Good luck, mate!
